language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: x7CaxsQoE6wtt535Xl+Ig5Lj3Vc+VAYc2FZPa5kScjUJmqThbV/CbDNd4gOi2uLvruxbNW0crZS6ikjKJnblANDVHZfcL2DBJZYyTYpl1X43gVICBDFZSdsJEoISf0lfHVW3LY3mNjAVNnbeYEhIgnlZrkrj82QmQhlAQpiQbfuJ2gUhqOdmxdzGOT22qODaf/Dg8WbryFZbyTmSSv9GDNBaBJecef1qXYQxmqJwWrWGXupIjuboNjG0YibZq3htxbaE3ixYp1WEtRl9sfjtgPndlUfRcDqE3pXfGpu4UV1rUQjUPBA3ZDH4bzJI37aWFyIWt6CCk21QY/mbxuc7jk0N48K+8wEt5NjgxMoGqpfbQH7yMzR6RWp8m+uZDBE68cYl7ohHDe8IyrUhvCeoribJtBYyf27xkjuR3CdnWlwyjcfoKQfn4+3ZI/tI94fGXqmAfSjspdNB7g2VGiKXLgZFlx0jy7v724n0YIWSuD46BpsCZGYOG2jbiDsfmrwLkOVi9sM5ZbnU7Nev6qEcHt6hGq2+5E4er346UItBvgOOIVwAuvQgAumEmGNhs/doA1D2oDAxHlgZX3TxgpN7IYtSIG9hH7D/k2arwGo8udsok4dT0qwZW7rVGGmnDHy9N8PqBb0ZwzyjedHZoqc4mlU3AEK9crxraSTLw/99ZDo=
after_success:
  - npx semantic-release
